secret: 1234567890123456
host:
port: 4080
database:
  driver: postgres
  dsn: postgres://macabro:macabro@localhost/macabro
  maxOpenConns: 50
  maxIdleConns: 5
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
