---
swagger: "2.0"
info:
  version: 1.0.0
  title: FreeLive

paths:
  /:
    $ref: "./basic/hello.yml"

  /metrics:
    $ref: "./basic/metrics.yml"

  /api/v1/auth/sing-up:
    $ref: "./auth/sing-up.yml"

  /api/v1/auth/sing-in:
    $ref: "./auth/sing-in.yml"
