---
swagger: "2.0"
info:
  version: 1.0.0
  title: FreeLive

definitions:
  User:
    $ref: "./schemas/user.yml"
  Session:
    $ref: "./schemas/session.yml"

securityDefinitions:
  # X-API-Key: abcdef12345
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
  # /path?api_key=abcdef12345
  APIKeyQueryParam:
    type: apiKey
    in: query
    name: token

security:
  - APIKeyHeader: []

paths:
  /:
    $ref: "./basic/hello.yml"

  /metrics:
    $ref: "./basic/metrics.yml"

  /api/v1/auth/sing-up:
    $ref: "./auth/sing-up.yml"

  /api/v1/auth/sing-in:
    $ref: "./auth/sing-in.yml"

  /api/v1/auth/session:
    $ref: "./auth/session.yml"

  /api/v1/users:
    $ref: "./users/index.yml"

  /api/v1/users/:user_id:
    $ref: "./users/crud.yml"
